title: Test Page (just the docs)
description: A test page using "just the docs template"
theme: just-the-docs

url: https://mgmegive.github.io/just-the-docs-test/

aux_links:
  Template Repository: https://github.com/mgmegive/just-the-docs-test

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/mgm.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/mgm.ico"
